<?php
/**
 * Block style variations enqueueing function and hook
 * 
 * @package	  basse
 * @since     0.1.0
 */



namespace basse;



// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}



/**
 * Enqueue block style variations css
 * 
 * The following are required for this function to work:
 * 
 * 1. All block style variations CSS files must be stored in "/assets/css/block/block-style-variations" directory.
 * 2. All block style variations CSS files must have the required file headers:
 *           
 *    - Name:              Required. The unique identifier/slug of the style variation.
 *    - Block Name:        Required. The block name of the block type where the style variation is applied. Must include namespace and block slug (e.g. core/group).
 *    - Class Name:        Required. The CSS Class Name generated by the style variations API for each specific variation (e.g., .is-style-{name}).
 *    - Loading Method:    Optional. The preferred loading Method. Optional. When provided, may be either 'inline' or 'external'. Default: 'inline'.
 *    - Critical:          Optional. Whether the CSS asset is a critial CSS or not. Only relevant when 'Loading Method' is 'external'. 
 *                         Default 'false'. Accepts 'true' or 'false'.     
 * 
 * @since 0.1.0
 * 
 * @see 'get_file_data()'
 * @see 'basse\dynamically_enqueue_custom_block_style()'
 */
function enqueue_block_style_variations_css() {

    // Scan the folder where the custom block patterns styles are located.
    $style_variations_css_file_paths = glob( THEME_DIR . '/assets/css/block/block-style-variations/*.css' );
    $style_variations_css_file_metadata = glob( THEME_DIR . '/assets/css/block/block-style-variations/*.php' );

    // Filter the array of all patterns CSS file paths to get only the default CSS file paths. 
    $style_variations_default_css_file_paths = array_values( array_filter( $style_variations_css_file_paths, function( $file_path ) {  return !str_contains( basename( $file_path ), '-rtl.css'); } ) );

    // Filter the array of all patterns CSS file paths to get only the RTL CSS file paths.
    $style_variations_rtl_css_file_paths = array_values( array_filter( $style_variations_css_file_paths, function( $file_path ) {  return str_contains( basename( $file_path ), '-rtl.css'); } ) );

    // Loop through all the default CSS file paths
    foreach( $style_variations_default_css_file_paths as $i => $file_path ) {

        // Default file headers
        $default_file_headers = array(
            'name'              =>  'Name',
            'block_name'        =>  'Block Name',
            'class_name'        =>  'Class Name',
            'loading_method'    =>  'Loading Method',
            'critical'          =>  'Critical'
        );

        // Get the file headers of the current file being loop through
        $css_file_headers = get_file_data( $file_path, $default_file_headers );

        // Get the CSS file metadata of the current file being loop through.
        $css_file_metadata = isset( $style_variations_css_file_metadata[$i] ) ? include  $style_variations_css_file_metadata[$i] : null;

        // If it is set, get the version number of the current file being 
        // loop through from the CSS file metadata.
        $version = $css_file_metadata['version'] ?? null;

        // Create asset handle
        $handle = THEME_NS . '-block-style-variation---' . str_replace('/', '-', $css_file_headers['block_name']) . '---' . $css_file_headers['name'];

        // Create asset source from $file_path
        $src = file_exists( $file_path ) ? str_replace( THEME_DIR, THEME_URI, $file_path ) : null;

        // Create array of dependencies from $css_file_headers['dependencies']
        $deps = !empty( $css_file_headers['dependencies'] ) ? explode( ',', $css_file_headers['dependencies'] ) : null;

        // Create the $args array that will be passed as an argument to the enqueue function
        $args = array();
        $args = array_merge( $args, array( 'handle' => $handle ) );
        $args = array_merge( $args, array( 'path' => $file_path ) );
        $args = !is_null( $src ) ? array_merge( $args, array( 'src' => $src ) ) : $args;
        $args = !is_null( $version ) ? array_merge( $args, array( 'ver' => $version ) ) : $args;
        $args = !empty( $css_file_headers['loading_method'] ) ? array_merge( $args, array( 'loading_method' => $css_file_headers['loading_method'] ) ) : $args;
        $args = !empty( $css_file_headers['critical'] ) ? array_merge( $args, array( 'critical' => filter_var( $css_file_headers['critical'], FILTER_VALIDATE_BOOLEAN ) ) ) : $args;

        // Enqueue the CSS asset using a custom function
        dynamically_enqueue_custom_block_style( 
            $css_file_headers['block_name'],
            $css_file_headers['class_name'], 
            $args
        );
    }
}
add_action( 'init', THEME_NS . '\enqueue_block_style_variations_css' );